services:
  rag-api:
    build: .
    container_name: rag-api
    ports:
      - "8000:8000"
    volumes:
      # 挂载数据目录
      - ./data:/app/data
      - ./local_models:/app/local_models
      - ./my_chromadb_vector_store:/app/my_chromadb_vector_store
      # 挂载配置文件
      - ./.env:/app/.env:ro
    environment:
      - LOG_LEVEL=INFO
      - WORKERS=4
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 可选：添加 Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: rag-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - rag-api
    restart: unless-stopped
    profiles:
      - with-nginx

  # 可选：添加 Redis 缓存
  redis:
    image: redis:alpine
    container_name: rag-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - with-cache

volumes:
  redis_data: